#Too old version -> too much problems
#Now, It is not possible to change the Docker version due to the installed operating system

version: '2.0'
services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgresQL
      POSTGRES_PASSWORD: postgresQL
      POSTGRES_DB: users_DB
#    ports:
#      - "5432:5432"
#    networks:
#      - local-net

# Apache Kafka (Parameters are from DockerHub)
#  Run Kafka in KRaft (instead Zookeeper)
  broker:
    image: apache/kafka:3.7.0-rc1
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

#    networks:
#      - local-net
#    healthcheck:
#      test: [ "CMD", "bash", "-c", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092" ]
#      interval: 10s          # checking interval
#      timeout: 5s            # waiting until checking complete
#      retries: 5             # count missing to «unhealthy»
#      start_period: 30s      # boot‑time

  # Email's consumer
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
# GUI
      - "8025:8025"
#    networks:
#      - local-net

  config-server:
    container_name: config-server
    build:
      context: ./config-server
#  Don't need to specify it if the filename is standard.
      dockerfile: Dockerfile
#  Download configuration from git.
    ports:
      - "8888:8888"
#    networks:
#      - local-net

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    depends_on:
      - config-server
#    networks:
#      - local-net
#    ports:
#      - "8761:8761"

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
#    networks:
#      - local-net

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    depends_on:
      - broker
      - gateway
      - mailhog
#    networks:
#      - local-net

  producer:
    container_name: producer
    build:
      context: ./springproject
    depends_on:
      - consumer
#    networks:
#      - local-net

#networks:
#  local-net:
#    driver: bridge
