version: '2.0'
services:
  db:
    image: postgres:14-alpine
    restart: always
    container_name: postgreSQL
    environment:
      POSTGRES_USER: postgresQL
      POSTGRES_PASSWORD: postgresQL
      POSTGRES_DB: users_DB

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'



# Email's consumer
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

# GUI
    ports:
      - "8025:8025"

  config-server:
    container_name: config-server
    build:
      context: ./config-server
#  Don't need to specify it if the filename is standard.
      dockerfile: Dockerfile

#  Download configuration from git.
    ports:
      - "8888:8888"
    hostname: config-server

  eureka-server:
    container_name: eureka-server
    build:
      context: ./eureka-server
    hostname: eureka-server
    depends_on:
      - config-server

  gateway:
    container_name: gateway
    build:
      context: ./gateway
    hostname: gateway
    depends_on:
      - eureka-server


# Connect to App
    ports:
      - "8080:8080"

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    hostname: consumer
    depends_on:
      - broker
      - gateway
      - mailhog

#  springproject:
#    container_name: springproject
#    hostname: springproject
#    build:
#      context: ./springproject
#    depends_on:
#      - consumer
